upload:
	scp api.py goldbergm@perlman.mathcs.carleton.edu:/var/www/html/cs257/goldbergm/webapp
	scp website.py goldbergm@perlman.mathcs.carleton.edu:/var/www/html/cs257/goldbergm/webapp
	scp -r templates goldbergm@perlman.mathcs.carleton.edu:/var/www/html/cs257/goldbergm/webapp
	scp -r static goldbergm@perlman.mathcs.carleton.edu:/var/www/html/cs257/goldbergm/webapp

login:
	ssh goldbergm@perlman.mathcs.carleton.edu;

runperlman:
	python3 api.py perlman.mathcs.carleton.edu 5105;



